from typing import Annotated, TypedDict, Optional, Union
import operator

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

from .schemas import (
    ImageChoice,
    ColourPaletteOption,
    MultiSelectTextOption,
    ScaleRating,
    FreeTextResponse,
    TextWithImageResponse,
    UserResponse,
    JourneySchema
)

# Type alias for UI input types
UIInputType = Union[
    ImageChoice,
    ColourPaletteOption,
    MultiSelectTextOption,
    ScaleRating,
    FreeTextResponse,
    TextWithImageResponse
]


class PersonalStylistState(TypedDict):
    """State for the Personal Stylist react agent."""

    # Conversation messages
    messages: Annotated[list[BaseMessage], add_messages]

    # UI components generated by the agent (accumulates across turns)
    ui_inputs: Annotated[list[dict], operator.add]

    # User responses to UI components (accumulates across turns)
    ui_answers: Annotated[list[UserResponse], operator.add]

    # Journey schema - progressively populated until agent is satisfied
    journey: Optional[JourneySchema]
