# Agent configs
## Merchant agents
### Catalogue ingestor config
catalogue_ingestor: &base_agent_recipe
  model: &base_model_recipe
    name: gemini-3-pro-preview
    params:
      temperature: 0.7
      max_tokens: 1024
      thinking_level: low
      include_thoughts: true

personal_stylist: *base_agent_recipe