# Agent configs
## Merchant agents
### Catalogue ingestor config
catalogue_ingestor: &base_agent_recipe
  model: &base_model_recipe
    name: gemini-3-pro-preview
    params: &base_model_params_recipe
      temperature: 0.7
      max_tokens: 2048
      thinking_level: low
      include_thoughts: true
  recursion_limit: 100
  enable_google_search_tool: false

## Consumer agents
### Personal stylist config
personal_stylist:
  <<: *base_agent_recipe
  model:
    <<: *base_model_recipe
    params:
      <<: *base_model_params_recipe
      thinking_level: low
      max_tokens: 4096
  recursion_limit: 25
  enable_google_search_tool: true

### Matchmaker config
matchmaker:
  <<: *base_agent_recipe
  model:
    <<: *base_model_recipe
    params:
      <<: *base_model_params_recipe
      thinking_level: low
      max_tokens: 4096
  recursion_limit: 25
  enable_google_search_tool: true

### Fitting room assistant config
fitting_assistant:
  <<: *base_agent_recipe
  model:
    <<: *base_model_recipe
    params:
      <<: *base_model_params_recipe
      thinking_level: low
      max_tokens: 4096
  recursion_limit: 25
  enable_google_search_tool: false